version: "3"

services:
  postgresql:
    extends:
      file: tools/database-dev/docker-compose.yml
      service: postgresql

  pgadmin:
    extends:
      file: tools/database-dev/docker-compose.yml
      service: pgadmin

  migrations_gateway:
    container_name: "migrations_gateway"
    image: liquibase/liquibase:4.19.0
    command: --defaultsFile=/app/liquibase.properties update
    depends_on:
      postgresql:
        condition: service_healthy
    volumes:
      - ./gateway/migrations:/app
    networks:
      - tracker-network

  gateway:
    container_name: "gateway"
    build:
      context: .
      dockerfile: gateway/src/Dockerfile
    depends_on:
      postgresql:
        condition: service_healthy
      migrations_gateway:
        condition: service_completed_successfully
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - tracker-network

networks:
  tracker-network:
    name: "tracker-network"
