# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

# import task_manager_pb2 as task__manager__pb2
from protos import task_manager_pb2 as task__manager__pb2


class TaskManagerServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/task_grpc.TaskManagerServer/CreateUser',
                request_serializer=task__manager__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=task__manager__pb2.CreateUserResponse.FromString,
                )
        self.CreateTask = channel.unary_unary(
                '/task_grpc.TaskManagerServer/CreateTask',
                request_serializer=task__manager__pb2.CreateTaskRequest.SerializeToString,
                response_deserializer=task__manager__pb2.CreateTaskResponse.FromString,
                )
        self.UpdateTask = channel.unary_unary(
                '/task_grpc.TaskManagerServer/UpdateTask',
                request_serializer=task__manager__pb2.UpdateTaskRequest.SerializeToString,
                response_deserializer=task__manager__pb2.UpdateTaskResponse.FromString,
                )
        self.DeleteTask = channel.unary_unary(
                '/task_grpc.TaskManagerServer/DeleteTask',
                request_serializer=task__manager__pb2.DeleteTaskRequest.SerializeToString,
                response_deserializer=task__manager__pb2.DeleteTaskResponse.FromString,
                )
        self.GetTask = channel.unary_unary(
                '/task_grpc.TaskManagerServer/GetTask',
                request_serializer=task__manager__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=task__manager__pb2.GetTaskResponse.FromString,
                )
        self.ListTasks = channel.unary_unary(
                '/task_grpc.TaskManagerServer/ListTasks',
                request_serializer=task__manager__pb2.ListTasksRequest.SerializeToString,
                response_deserializer=task__manager__pb2.ListTasksResponse.FromString,
                )


class TaskManagerServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskManagerServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=task__manager__pb2.CreateUserRequest.FromString,
                    response_serializer=task__manager__pb2.CreateUserResponse.SerializeToString,
            ),
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=task__manager__pb2.CreateTaskRequest.FromString,
                    response_serializer=task__manager__pb2.CreateTaskResponse.SerializeToString,
            ),
            'UpdateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTask,
                    request_deserializer=task__manager__pb2.UpdateTaskRequest.FromString,
                    response_serializer=task__manager__pb2.UpdateTaskResponse.SerializeToString,
            ),
            'DeleteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTask,
                    request_deserializer=task__manager__pb2.DeleteTaskRequest.FromString,
                    response_serializer=task__manager__pb2.DeleteTaskResponse.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=task__manager__pb2.GetTaskRequest.FromString,
                    response_serializer=task__manager__pb2.GetTaskResponse.SerializeToString,
            ),
            'ListTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=task__manager__pb2.ListTasksRequest.FromString,
                    response_serializer=task__manager__pb2.ListTasksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'task_grpc.TaskManagerServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TaskManagerServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/task_grpc.TaskManagerServer/CreateUser',
            task__manager__pb2.CreateUserRequest.SerializeToString,
            task__manager__pb2.CreateUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/task_grpc.TaskManagerServer/CreateTask',
            task__manager__pb2.CreateTaskRequest.SerializeToString,
            task__manager__pb2.CreateTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/task_grpc.TaskManagerServer/UpdateTask',
            task__manager__pb2.UpdateTaskRequest.SerializeToString,
            task__manager__pb2.UpdateTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/task_grpc.TaskManagerServer/DeleteTask',
            task__manager__pb2.DeleteTaskRequest.SerializeToString,
            task__manager__pb2.DeleteTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/task_grpc.TaskManagerServer/GetTask',
            task__manager__pb2.GetTaskRequest.SerializeToString,
            task__manager__pb2.GetTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/task_grpc.TaskManagerServer/ListTasks',
            task__manager__pb2.ListTasksRequest.SerializeToString,
            task__manager__pb2.ListTasksResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
