@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!include DEVICONS/angular.puml
!include DEVICONS/postgresql.puml
!include DEVICONS/python.puml
!include <cloudinsight/kafka>

title
    <b>C4 диаграмма контейнеров</b>
end title

Person(user, "Пользователь", "Пользователь сервиса")

' Container(front, "Сайт трекера задач", "Angular", $sprite="angular")
Container(gateway, "Gateway", "python", $sprite="python")
ContainerDb(gateway_db, "Database", "PostgreSQL", $sprite="postgresql")
Container(statistics, "Statistics", "python", $sprite="python")
ContainerDb(statistics_db, "Database", "Clickhouse")
Container(task_manager, "Task manager", "python", $sprite="python")
ContainerDb(task_manager_db, "Database", "PostgreSQL", $sprite="postgresql")
ContainerQueue(event, "event queue", "kafka", "", "kafka")

Rel(user, gateway, "Регистрация, аутентификация, API пользователя", "Rest")
Rel(gateway, statistics, "Запросы на просмотр статистики лайков/просмотров ", "gRPC")
Rel(gateway, task_manager, "Запросы для составление комментариев", "gRPC")
Rel_L(gateway, gateway_db, "Read/Write")
Rel_L(statistics, statistics_db, "Read/Write")
Rel_R(task_manager, task_manager_db, "Read/Write")
Rel(task_manager, event, "Сообщение о просмотре/лайке")
Rel(event, statistics, "Читает сообщение")

@enduml